CREATE TABLE TEMP_TB_SY_CMCD_GRP_20230707
(
  CD_GRP_ID	VARCHAR2(20 BYTE)
, CD_GRP_NM	VARCHAR2(200 BYTE)
, BIZ_FG	VARCHAR2(20 BYTE)
, USE_YN	VARCHAR2(1 BYTE)
);


INSERT INTO TB_SY_CMCD_GRP
SELECT CD_GRP_ID
     , CD_GRP_NM
     , 10
     , BIZ_FG
     , USE_YN
     , NULL
     , NULL
     , NULL
     , NULL
     , NULL
     , NULL
     , NULL
     , NULL
     , NULL
     , NULL
     , NULL
     , 'SYSTEM'
     , SYSDATE
     , 'SYSTEM'
     , SYSDATE
     , SYSDATE
     , NULL
  FROM TEMP_TB_SY_CMCD_GRP_20230707
 GROUP BY CD_GRP_ID
        , CD_GRP_NM
		, BIZ_FG
		, USE_YN
;


CREATE TABLE TEMP_TB_SY_CMCD_20230707
(
  CD_GRP_ID	VARCHAR2(20 BYTE)
, CD_ID	VARCHAR2(20 BYTE)
, CD_NM	VARCHAR2(200 BYTE)
, SORT_ORD	NUMBER(5,0)
, USE_YN	VARCHAR2(1 BYTE)
, REF_VAL1	VARCHAR2(500 BYTE)
, REF_VAL2	VARCHAR2(500 BYTE)
, REF_VAL3	VARCHAR2(500 BYTE)
, REF_VAL4	VARCHAR2(500 BYTE)
, REF_VAL5	VARCHAR2(500 BYTE)
, REF_VAL6	VARCHAR2(500 BYTE)
, REF_VAL7	VARCHAR2(500 BYTE)
, REF_VAL8	VARCHAR2(500 BYTE)
, REF_VAL9	VARCHAR2(500 BYTE)
, REF_VAL10	VARCHAR2(500 BYTE)
, RMRK	VARCHAR2(4000 BYTE)
);

-- 중복 데이터 PK 오류
SELECT CD_GRP_ID, CD_ID
  FROM TEMP_TB_SY_CMCD_20230707
 GROUP BY CD_GRP_ID, CD_ID
 HAVING COUNT(*) > 1
;

-- 코드명이 NULL 인 데이터 오류
SELECT *
  FROM TEMP_TB_SY_CMCD_20230707
 WHERE CD_NM IS NULL
;

INSERT INTO TB_SY_CMCD
SELECT CD_GRP_ID
     , CD_ID
     , NVL2(CD_NM, CD_NM, '임시') AS CD_NM
     , SORT_ORD
     , USE_YN
     , REF_VAL1
     , REF_VAL2
     , REF_VAL3
     , REF_VAL4
     , REF_VAL5
     , REF_VAL6
     , REF_VAL7
     , REF_VAL8
     , REF_VAL9
     , REF_VAL10
     , RMRK
     , 'SYSTEM'
     , SYSDATE
     , 'SYSTEM'
     , SYSDATE
     , SYSDATE
     , NULL
  FROM TEMP_TB_SY_CMCD_20230707
 WHERE ( CD_GRP_ID, CD_ID, USE_YN ) NOT IN ( ('DP010','1102325','N') , ('DP010','1102337','N') )
;


